/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author praktek
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        //this.setSize(1000, 600);
        setLocationRelativeTo(this);
        Koneksi.DataBase.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnLayerBarang = new javax.swing.JButton();
        btnLayerSuplier = new javax.swing.JButton();
        btnLayerBarang1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnLayerBuktiPesan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLayerLapBarang = new javax.swing.JButton();
        a = new javax.swing.JButton();
        btnLayerLapSuplier = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MMenu = new javax.swing.JMenu();
        MKategori = new javax.swing.JMenuItem();
        MBarang1 = new javax.swing.JMenuItem();
        MSuplier = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        TBuktiPesan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        LPelanggan = new javax.swing.JMenuItem();
        LBarang = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Mexit = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Penjualan Windy Collection");

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLayerBarang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btnLayerBarang.setText("BARANG");
        btnLayerBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerBarangActionPerformed(evt);
            }
        });

        btnLayerSuplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerSuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btnLayerSuplier.setText("SUPLIER");
        btnLayerSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerSuplierActionPerformed(evt);
            }
        });

        btnLayerBarang1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerBarang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btnLayerBarang1.setText("KATEGORI");
        btnLayerBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerBarang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLayerBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayerSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayerBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLayerBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLayerBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnLayerSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLayerBuktiPesan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerBuktiPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buy.png"))); // NOI18N
        btnLayerBuktiPesan.setToolTipText("Buat Bukti Pesan");
        btnLayerBuktiPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerBuktiPesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnLayerBuktiPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnLayerBuktiPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLayerLapBarang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerLapBarang.setText("LAPORAN PENDAPATAN");
        btnLayerLapBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerLapBarangActionPerformed(evt);
            }
        });

        a.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a.setText("LAPORAN STOK");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        btnLayerLapSuplier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLayerLapSuplier.setText("LAPORAN SUPLIER");
        btnLayerLapSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayerLapSuplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLayerLapBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLayerLapSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLayerLapBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLayerLapSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("GROBOLD", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Windy Collection");

        MMenu.setText("File Master");

        MKategori.setText("Entry Data Kategori");
        MKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKategoriActionPerformed(evt);
            }
        });
        MMenu.add(MKategori);

        MBarang1.setText("Entry Data Barang");
        MBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBarang1ActionPerformed(evt);
            }
        });
        MMenu.add(MBarang1);

        MSuplier.setText("Entry Data Suplier");
        MMenu.add(MSuplier);

        MenuExit.setText("Exit");
        MenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuExitMouseClicked(evt);
            }
        });
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MMenu.add(MenuExit);

        jMenuBar1.add(MMenu);

        jMenu2.setText("Transaksi");

        TBuktiPesan.setText("Bukti Pesan");
        TBuktiPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBuktiPesanActionPerformed(evt);
            }
        });
        jMenu2.add(TBuktiPesan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        LPelanggan.setText("Laporan Pendapatan");
        LPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(LPelanggan);

        LBarang.setText("Laporan Data Barang");
        LBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBarangActionPerformed(evt);
            }
        });
        jMenu3.add(LBarang);

        jMenuItem1.setText("Laporan Data Suplier");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        Mexit.setText("Exit");
        Mexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexitMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mexit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        setSize(new java.awt.Dimension(716, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MexitMouseClicked

    private void LPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPelangganActionPerformed
        View.LapPendapatan P = new View.LapPendapatan();
         P.setVisible(true);   
         setLocationRelativeTo(this); 
         P.getTgl1().requestFocus();
    }//GEN-LAST:event_LPelangganActionPerformed

    private void LBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBarangActionPerformed
        View.LapStok B = new View.LapStok();
        B.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_LBarangActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuExitMouseClicked

    }//GEN-LAST:event_MenuExitMouseClicked

    private void MBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBarang1ActionPerformed
        View.MBarang B = new MBarang();
        B.setVisible(true);
        setLocationRelativeTo(this);
        B.getTxtnmbarang().requestFocus();
    }//GEN-LAST:event_MBarang1ActionPerformed

    private void MKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKategoriActionPerformed
        View.MKategoriBarang k = new MKategoriBarang();
        k.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_MKategoriActionPerformed

    private void TBuktiPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBuktiPesanActionPerformed
        View.TBuktiPesan T = new View.TBuktiPesan();
         T.setVisible(true); 
         setLocationRelativeTo(this);
    }//GEN-LAST:event_TBuktiPesanActionPerformed

    private void btnLayerBuktiPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerBuktiPesanActionPerformed
        View.TBuktiPesan T = new View.TBuktiPesan();
        T.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerBuktiPesanActionPerformed

    private void btnLayerLapSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerLapSuplierActionPerformed
        View.LapSuplier S = new LapSuplier();
        S.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerLapSuplierActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        View.LapStok B = new View.LapStok();
        B.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_aActionPerformed

    private void btnLayerLapBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerLapBarangActionPerformed
        View.LapPendapatan P = new View.LapPendapatan();
        P.setVisible(true);
        setLocationRelativeTo(this);
        P.getTgl1().requestFocus();
    }//GEN-LAST:event_btnLayerLapBarangActionPerformed

    private void btnLayerBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerBarangActionPerformed
        View.MBarang B = new MBarang();
        B.setVisible(true);
        setLocationRelativeTo(this);
        B.getTxtnmbarang().requestFocus();
    }//GEN-LAST:event_btnLayerBarangActionPerformed

    private void btnLayerSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerSuplierActionPerformed
        View.MSuplier S = new MSuplier();
        S.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerSuplierActionPerformed

    private void btnLayerBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayerBarang1ActionPerformed
        View.MKategoriBarang k = new MKategoriBarang();
        k.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_btnLayerBarang1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LBarang;
    private javax.swing.JMenuItem LPelanggan;
    private javax.swing.JMenuItem MBarang1;
    private javax.swing.JMenuItem MKategori;
    private javax.swing.JMenu MMenu;
    private javax.swing.JMenuItem MSuplier;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu Mexit;
    private javax.swing.JMenuItem TBuktiPesan;
    private javax.swing.JButton a;
    private javax.swing.JButton btnLayerBarang;
    private javax.swing.JButton btnLayerBarang1;
    private javax.swing.JButton btnLayerBuktiPesan;
    private javax.swing.JButton btnLayerLapBarang;
    private javax.swing.JButton btnLayerLapSuplier;
    private javax.swing.JButton btnLayerSuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
